export const IPC = {
  appInfo: 'app:info',
  appOpenLogs: 'app:open-logs',
  libraryList: 'library:list',
  libraryPickFolder: 'library:pick-folder',
  libraryImportFolder: 'library:import-folder',
  libraryFolders: 'library:folders',
  libraryRescan: 'library:rescan',
  libraryRemoveMissing: 'library:remove-missing',
  songGet: 'song:get',
  songCheckFiles: 'song:check-files',
  songMarkPlayed: 'song:mark-played',
  songUpdateMetadata: 'song:update-metadata',
  songSetFavorite: 'song:set-favorite',
  queueList: 'queue:list',
  queueAdd: 'queue:add',
  queueRemove: 'queue:remove',
  queueMove: 'queue:move',
  queueSetStatus: 'queue:set-status',
  queueClear: 'queue:clear',
  historyList: 'history:list',
  historyClear: 'history:clear',
  melodyGet: 'melody:get',
  melodySetTrack: 'melody:set-track',
  voiceArm: 'voice:arm',
  voiceActive: 'voice:active',
  log: 'log:write'
} as const
